group_wb: Test

# Training config
beggining_sample: Les Dofus sont à votre portée
n_epochs: 20
batch_size: 16
lr: 1.0e-4
reg_weight: 1.0e-2

# General config
model_name: asi/gpt-fr-cased-small
dataset_path: data/data.csv
device: cuda
seed: 0
