group_wb: GPT2 128M

# Training config
beggining_sample: Les Dofus sont à votre portée
n_epochs: 5
batch_size: 32
lr: 1.0e-4
reg_weight: 1.0e-2

# General config
model_name: asi/gpt-fr-cased-small
dataset_path: data/big_file.txt
device: cuda
seed: 0
